version: 2
jobs:
  build-my:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/my-appd
    branches:
      only:
        - master
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-appd
      - run: pwd
      # - run:
      #     name: FIRST STEP
      #     command: |
      #       echo 'Hello World!'
      #       echo 'This is the delivery pipeline'
      #       cat /etc/os-release
      # - run:
      #     name: TWO STEP
      #     command: |
      #       ls -la
      #       pwd
workflows:
  version: 2
  workflow:
    jobs:
      - build-my
